name: New Lab
description: Form for adding a new lab
labels: new-lab
title: Add Name of Lab
body:
  - type: textarea
    id: lab-name
    attributes: 
      label: Name of Lab
      description: Name of the lab/group or, "<Surname of PI> Lab".
    validations:
      required: true
  - type: textarea
    id: lab-pi
    attributes: 
      label: Name of PI
      description: The name of the Principal Investigator with Academic Title (e.g. Prof. Dr. Jane Smith).
    validations:
      required: true
  - type: textarea
    id: lab-institution
    attributes: 
      label: Name of Institution
      description: Name of institution of that the lab or group the ancient metagenomic work is happening in. Preferably in official/main language of country, however must be searchable on Google Maps, and result in the address as the first result (for mapping purposes).
    validations:
      required: true
  - type: textarea
    id: lab-country
    attributes: 
      label: Country of Institution
      description: Country that the institution is located in.
    validations:
      required: true
  - type: textarea
    id: lab-webpage
    attributes: 
      label: Webpage of the lab or group
      description: URL to the webpage of the PI/group/lab/institution.
    validations:
      required: true
  - type: checkboxes
    id: lab-topic
    label: Research focus
    attributes:
      options:
        - label: anthropogenic
          description:  e.g. from human-made objects (pots, parchmeent etc.)
        - label: host-associated
          description: e.g. microbiomes derived directly from bodies of organisms
        - label: microbial-genomics
          description: e.g. microbial or viral pathogen genomes
        - label: environmental
          description: e.g.  e.g. from sedaDNA, either microbial or eukaryotes
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
    label: Other information
    description: Any other information
